name: flutter_app_zhkj_master
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  dio: ^2.1.13
  json_annotation: ^2.0.0
  fluttertoast: ^3.1.2
  fluro: ^1.5.1
  rxdart: ^0.22.0
  event_bus: ^1.1.0
  image_picker: ^0.6.1+4
  shared_preferences: ^0.5.3+4
  provider: ^3.1.0
  pull_to_refresh: ^1.5.6
  flutter_webview_plugin: 0.3.8
  flutter_alipay: 0.1.2
  fluwx: 1.0.6
  qr_flutter: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 运行"flutter packages pub run build_runner build"，生成.g辅助文件。
  # 运行"flutter packages pub run build_runner watch"，可以实现文件监听，自动地为你后续创建的实体类生成对应的解析代码。 # 运行"flutter packages pub run build_runner watch"，生成.g辅助文件。
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
flutter:

  uses-material-design: true
  assets:
   - assets/images/
